server:
  name: terrateam-server
  replicaCount: 1
  dns_name: ""
  db_host: terrateam-db
  db_port: 5432
  db_user: terrateam
  db_name: terrateam
  github_webhook_url_update: "true"
  self_hosted_infracost_api_key: ""
  infracost_pricing_api_endpoint: ""
  telemetry_level: "anonymous"
  image:
    repository: ghcr.io/terrateamio/terrateam
    tag: "v1"
    pullPolicy: Always
  resources:
    limits:
      cpu: 500m
      memory: 512Mi
    requests:
      cpu: 250m
      memory: 512Mi

db:
  enabled: true
  name: terrateam-db
  user: terrateam
  db_name: terrateam
  storage: "1Gi"
  storageClassName: "standard-rwo"
  image:
    repository: postgres
    tag: "14.5-alpine"
    pullPolicy: IfNotPresent
  resources:
    limits:
      cpu: 500m
      memory: 512Mi
    requests:
      cpu: 250m
      memory: 512Mi

ingress:
  enabled: false
  name: terrateam
  annotations: {}

certificate:
  enabled: false
