---
{{- if .Values.db.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.db.name }}
  {{- with (mergeOverwrite .Values.global.annotations .Values.db.annotations) }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  labels:
    app: {{ .Values.db.name }}
    {{- with (mergeOverwrite .Values.global.labels .Values.db.labels) }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: {{ .Values.db.name }}
  template:
    metadata:
      {{- with (mergeOverwrite .Values.global.annotations .Values.db.annotations) }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        app: {{ .Values.db.name }}
        {{- with (mergeOverwrite .Values.global.labels .Values.db.labels) }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      {{- with (coalesce .Values.db.nodeSelector .Values.global.nodeSelector) }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with (coalesce .Values.db.tolerations .Values.global.tolerations) }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with (coalesce .Values.db.affinity .Values.global.affinity) }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with (coalesce .Values.db.securityContext .Values.global.securityContext) }}
      securityContext:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with (coalesce .Values.db.imagePullSecrets .Values.global.imagePullSecrets) }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: {{ .Values.db.name }}
          image: {{ printf "%s:%s" .Values.db.image.repository .Values.db.image.tag }}
          imagePullPolicy: {{ .Values.db.image.pullPolicy }}
          {{- with .Values.db.resources }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          env:
            - name: "PGDATA"
              value: "/var/lib/postgresql/data/terrateam"
            - name: "PGPORT"
              value: {{ .Values.db.config.port | default 5432 | quote }}
            - name: "POSTGRES_DB"
              value: {{ .Values.db.config.databaseName | quote }}
            - name: "POSTGRES_USER"
              value: {{ .Values.db.config.username | quote }}
            - name: "POSTGRES_PASSWORD"
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.db.config.passwordSecretName }}
                  key: {{ .Values.db.config.passwordSecretKey }}
            {{- if .Values.db.config.extraEnv }}
            {{- toYaml .Values.db.config.extraEnv | nindent 12 }}
            {{- end }}
          ports:
            - name: postgres
              containerPort: {{ .Values.db.config.port | default 5432 }}
              protocol: TCP
          livenessProbe:
            exec:
              command:
                - "pg_isready"
                - "-d"
                - {{ .Values.db.config.databaseName | quote }}
                - "-U"
                - {{ .Values.db.config.username | quote }}
            initialDelaySeconds: 10
            periodSeconds: 5
            timeoutSeconds: 5
            failureThreshold: 6
          readinessProbe:
            exec:
              command:
                - "pg_isready"
                - "-d"
                - {{ .Values.db.config.databaseName | quote }}
                - "-U"
                - {{ .Values.db.config.username | quote }}
            initialDelaySeconds: 5
            periodSeconds: 5
            timeoutSeconds: 3
            failureThreshold: 3
          volumeMounts:
            - mountPath: /var/lib/postgresql/data/
              name: terrateam-db-data-volume
      volumes:
        - name: terrateam-db-data-volume
          persistentVolumeClaim:
            claimName: {{ .Values.db.pvc.name }}
{{- end -}}
