---
{{- if .Values.db.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.db.service.name | default .Values.db.name }}
  {{- with (mergeOverwrite .Values.global.annotations .Values.db.annotations .Values.db.service.annotations) }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  labels:
    app: {{ .Values.db.name }}
    {{- with (mergeOverwrite .Values.global.labels .Values.db.labels .Values.db.service.labels) }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  type: {{ .Values.db.service.type | default "ClusterIP" }}
  ports:
    - name: postgres
      protocol: TCP
      port: {{ .Values.db.service.port | default .Values.db.config.port | default 5432 }}
      targetPort: {{ .Values.db.config.port | default 5432 }}
      {{- if and (eq .Values.db.service.type "NodePort") .Values.db.service.nodePort }}
      nodePort: {{ .Values.db.service.nodePort }}
      {{- end }}
  selector:
    app: {{ .Values.db.name }}
{{- end }}
