---
{{- if .Values.db.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.db.name | quote }}
  labels:
    app: {{ .Values.db.name | quote }}
spec:
  type: {{ .Values.db.serviceType | default "NodePort"}}
  ports:
    - port: 5432
      targetPort: 5432
      {{- if and (eq .Values.db.serviceType "NodePort") .values.db.nodePort }}
      nodePort: {{ .Values.db.nodePort }}
      {{- end }}
  selector:
    app: {{ .Values.db.name | quote }}
{{- end }}
