---
{{- if .Values.db.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: terrateam-db-data-claim
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: "{{ .Values.db.storage }}"
  storageClassName: "{{ .Values.db.storageClassName }}"
{{- end -}}
