---
{{- if .Values.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Values.ingress.name }}
  {{- with .Values.ingress.annotations }}
  annotations:
{{ toYaml . | indent 4 }}
  {{- end }}
spec:
  {{- if .Values.ingress.className }}
  ingressClassName: {{ .Values.ingress.className }}
  {{- end }}
  {{- if and .Values.ingress.useTls }}
  tls:
  - hosts:
    - {{ .Values.terrateam.config.fqdn | quote }}
    secretName: {{ .Values.ingress.tlsSecretName }}
  {{- end }}
  rules:
  - host: {{ .Values.terrateam.config.fqdn | quote }}
    http:
      paths:
      - pathType: ImplementationSpecific
        backend:
          service:
            name: {{ .Values.terrateam.service.name | quote }}
            port:
              number: 8080
{{- end -}}
