---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.server.name | quote }}
  labels:
    app: {{ .Values.server.name | quote }}
spec:
  type: {{ .Values.server.serviceType | default "NodePort"}}
  ports:
    - port: 8080
      targetPort: 8080
      {{- if and (eq .Values.server.serviceType "NodePort") .values.server.nodePort }}
      nodePort: {{ .Values.server.nodePort }}
      {{- end }}
  selector:
    app: {{ .Values.server.name | quote }}