---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.terrateam.name }}
  labels:
    app: {{ .Values.terrateam.name }}
spec:
  replicas: {{ .Values.terrateam.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Values.terrateam.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.terrateam.name }}
    spec:
      containers:
        - name: {{ .Values.terrateam.name }}
          image: "{{ .Values.terrateam.image.repository }}:{{ .Values.terrateam.image.tag }}"
          imagePullPolicy: {{ .Values.terrateam.image.pullPolicy }}
          resources:
            limits:
              cpu: "{{ .Values.terrateam.resources.limits.cpu }}"
              memory: "{{ .Values.terrateam.resources.limits.memory}}"
            requests:
              cpu: "{{ .Values.terrateam.resources.requests.cpu }}"
              memory: "{{ .Values.terrateam.resources.requests.memory }}"
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 15
          readinessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 15
          env:
            - name: "TERRAT_API_BASE"
              value: "https://{{ .Values.terrateam.dns_name }}/api"
            - name: "GITHUB_WEBHOOK_URL_UPDATE"
              value: "{{ .Values.terrateam.github_webhook_url_update }}"
            - name: "SELF_HOSTED_INFRACOST_API_KEY"
              value: "{{ .Values.terrateam.self_hosted_infracost_api_key }}"
            - name: "INFRACOST_PRICING_API_ENDPOINT"
              value: "{{ .Values.terrateam.infracost_pricing_api_endpoint }}"
            - name: "TERRAT_TELEMETRY_LEVEL"
              value: "{{ .Values.terrateam.telemetry_level }}"
            - name: "TERRAT_WEB_BASE_URL"
              value: "{{ .Values.terrateam.web_base_url | default .Values.terrateam.dns_name }}"
            - name: "DB_HOST"
              value: "{{ .Values.terrateam.db_host }}"
            - name: "DB_PORT"
              value: "{{ .Values.terrateam.db_port }}"
            - name: "DB_USER"
              value: "{{ .Values.terrateam.db_user }}"
            - name: "DB_PASS"
              valueFrom:
                secretKeyRef:
                  name: terrateam-db-password
                  key: password
            - name: "DB_NAME"
              value: "{{ .Values.terrateam.db_name }}"
            - name: "GITHUB_WEBHOOK_SECRET"
              valueFrom:
                secretKeyRef:
                  name: terrateam-github-webhook-secret
                  key: secret
            - name: "GITHUB_APP_CLIENT_SECRET"
              valueFrom:
                secretKeyRef:
                  name: terrateam-github-app-client-secret
                  key: secret
            - name: "GITHUB_APP_CLIENT_ID"
              valueFrom:
                secretKeyRef:
                  name: terrateam-github-app-client-id
                  key: id
            - name: "GITHUB_APP_ID"
              valueFrom:
                secretKeyRef:
                  name: terrateam-github-app-id
                  key: id
            - name: "GITHUB_APP_PEM"
              valueFrom:
                secretKeyRef:
                  name: terrateam-github-app-pem
                  key: pem
