---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.terrateam.name }}
  {{- with (mergeOverwrite .Values.global.annotations .Values.terrateam.annotations) }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  labels:
    app: {{ .Values.terrateam.name }}
    {{- with (mergeOverwrite .Values.global.labels .Values.terrateam.labels) }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  replicas: {{ .Values.terrateam.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Values.terrateam.name }}
  template:
    metadata:
      {{- with (mergeOverwrite .Values.global.annotations .Values.terrateam.annotations) }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        app: {{ .Values.terrateam.name }}
        {{- with (mergeOverwrite .Values.global.labels .Values.terrateam.labels) }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      {{- with (coalesce .Values.terrateam.nodeSelector .Values.global.nodeSelector) }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with (coalesce .Values.terrateam.tolerations .Values.global.tolerations) }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with (coalesce .Values.terrateam.affinity .Values.global.affinity) }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with (coalesce .Values.terrateam.securityContext .Values.global.securityContext) }}
      securityContext:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with (coalesce .Values.terrateam.imagePullSecrets .Values.global.imagePullSecrets) }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: {{ .Values.terrateam.name }}
          image: {{ printf "%s:%s" .Values.terrateam.image.repository .Values.terrateam.image.tag }}
          imagePullPolicy: {{ .Values.terrateam.image.pullPolicy }}
          {{- with .Values.terrateam.resources }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 15
          readinessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 15
          env:
            - name: "TERRAT_API_BASE"
              value: "https://{{ .Values.terrateam.dns_name }}/api"
            - name: "GITHUB_WEBHOOK_URL_UPDATE"
              value: "{{ .Values.terrateam.github_webhook_url_update }}"
            - name: "SELF_HOSTED_INFRACOST_API_KEY"
              value: "{{ .Values.terrateam.self_hosted_infracost_api_key }}"
            - name: "INFRACOST_PRICING_API_ENDPOINT"
              value: "{{ .Values.terrateam.infracost_pricing_api_endpoint }}"
            - name: "TERRAT_TELEMETRY_LEVEL"
              value: "{{ .Values.terrateam.telemetry_level }}"
            - name: "TERRAT_WEB_BASE_URL"
              value: "{{ .Values.terrateam.web_base_url | default .Values.terrateam.dns_name }}"
            - name: DB_HOST
              value: {{ .Values.terrateam.config.db.hostname | quote }}
            - name: DB_PORT
              value: {{ .Values.terrateam.config.db.port | default 5432 | quote }}
            - name: DB_USER
              value: {{ .Values.terrateam.config.db.username | quote }}
            - name: DB_PASS
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.terrateam.config.db.passwordSecretName }}
                  key: {{ .Values.terrateam.config.db.passwordSecretKey }}
            - name: DB_NAME
              value: {{ .Values.terrateam.config.db.databaseName | quote }}
            - name: GITHUB_APP_ID
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.terrateam.github.appIdSecretName }}
                  key: {{ .Values.terrateam.github.appIdSecretKey }}
            - name: GITHUB_APP_CLIENT_ID
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.terrateam.github.appClientIdSecretName }}
                  key: {{ .Values.terrateam.github.appClientIdSecretKey }}
            - name: GITHUB_APP_CLIENT_SECRET
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.terrateam.github.appClientSecretSecretName }}
                  key: {{ .Values.terrateam.github.appClientSecretSecretKey }}
            - name: GITHUB_APP_PEM
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.terrateam.github.appPrivatePEMCertificateSecretName }}
                  key: {{ .Values.terrateam.github.appPrivatePEMCertificateSecretKey }}
            - name: GITHUB_WEBHOOK_SECRET
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.terrateam.github.webhookSecretName }}
                  key: {{ .Values.terrateam.github.webhookSecretKey }}

            {{- if .Values.terrateam.config.extraEnv }}
            {{- toYaml .Values.terrateam.config.extraEnv | nindent 12 }}
            {{- end }}
